import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const readSource = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('friend api wrapper targets the backend friend routes', async () => {
  const source = await readSource('src/services/friendApi.js')

  assert.match(source, /const FRIEND_API_PATH = "\/friends"/)
  assert.match(source, /getFriends\(playerId\)/)
  assert.match(source, /requests\/received/)
  assert.match(source, /requests\/sent/)
  assert.match(source, /requests\/\$\{requestId\}\/accept/)
  assert.match(source, /requests\/\$\{requestId\}\/reject/)
  assert.match(source, /apiClient\.delete\(`\$\{FRIEND_API_PATH\}\/\$\{friendshipId\}`/)
  assert.match(source, /\/blocks/)
  assert.match(source, /blocks\/\$\{blockId\}\/unblock/)
})

test('friend store uses real api data instead of friend mock data', async () => {
  const source = await readSource('src/stores/friendStore.js')

  assert.match(source, /from "@\/services\/friendApi\.js"/)
  assert.match(source, /searchPlayers as searchPlayersApi/)
  assert.match(source, /loadFriendData/)
  assert.match(source, /sendFriendRequestApi/)
  assert.match(source, /acceptFriendRequestApi/)
  assert.match(source, /rejectFriendRequestApi/)
  assert.match(source, /blockPlayer as blockPlayerApi/)
  assert.match(source, /removeFriend as removeFriendApi/)
  assert.match(source, /unblockPlayer as unblockPlayerApi/)
  assert.match(source, /blockedPlayers/)
  assert.match(source, /canUseFriendSystem/)
  assert.match(source, /friendLoginRequiredMessage/)
  assert.match(source, /authStore\.isLoggedIn/)
  assert.match(source, /authStore\.token/)
  assert.match(source, /removeFriend\(friendshipId\)/)
  assert.match(source, /blockPlayer\(targetPlayerId\)/)
  assert.match(source, /unblockPlayer\(blockId\)/)
  assert.doesNotMatch(source, /guestPlayer/)
  assert.doesNotMatch(source, /usePlayerStore/)
  assert.doesNotMatch(source, /playerStore/)
  assert.doesNotMatch(source, /localStorage/)
  assert.doesNotMatch(source, /friendMockData/)
  assert.doesNotMatch(source, /mockFriends/)
  assert.doesNotMatch(source, /mockFriendMessages/)
  assert.doesNotMatch(source, /selectedFriendMessages/)
})

test('friend view removes chat mock flow and shows friend details', async () => {
  const source = await readSource('src/views/FriendView.vue')

  assert.match(source, /friendStore\.loadFriendData\(\)/)
  assert.match(source, /selectedFriendDetails/)
  assert.match(source, /好友聊天尚未串接/)
  assert.match(source, /activeTab === 'blocks'/)
  assert.match(source, /BlockedPlayerList/)
  assert.match(source, /confirmRemoveFriend/)
  assert.match(source, /confirmBlockPlayer/)
  assert.match(source, /FriendAuthRequiredState/)
  assert.match(source, /friendStore\.canUseFriendSystem/)
  assert.match(source, /:disabled="!friendStore\.canUseFriendSystem"/)
  assert.doesNotMatch(source, /v-model="messageText"/)
  assert.doesNotMatch(source, /輸入訊息/)
  assert.doesNotMatch(source, /selectedFriendMessages/)
  assert.doesNotMatch(source, /sendMessage/)
})

test('add friend form searches players before sending invites', async () => {
  const source = await readSource('src/components/friend/AddFriendForm.vue')

  assert.match(source, /defineEmits\(\["search", "add-friend", "block-player"\]\)/)
  assert.match(source, /搜尋玩家/)
  assert.match(source, /searchResults/)
  assert.match(source, /relationStatus/)
  assert.match(source, /blockActionLabel/)
  assert.match(source, /emit\('block-player', player\)/)
  assert.match(source, /emit\("search", value\)/)
  assert.match(source, /emit\('add-friend', player\.playerId\)/)
})

test('friend list and blocked list expose relationship management controls', async () => {
  const friendListSource = await readSource('src/components/friend/FriendList.vue')
  const friendItemSource = await readSource('src/components/friend/FriendItem.vue')
  const blockedListSource = await readSource('src/components/friend/BlockedPlayerList.vue')

  assert.match(friendListSource, /showActions/)
  assert.match(friendListSource, /@remove="emit\('remove', \$event\)"/)
  assert.match(friendListSource, /@block="emit\('block', \$event\)"/)
  assert.match(friendItemSource, /解除好友/)
  assert.match(friendItemSource, /封鎖/)
  assert.match(blockedListSource, /取消封鎖/)
  assert.match(blockedListSource, /defineEmits\(\["unblock"\]\)/)
})

test('friend page and panel expose locked login-only state', async () => {
  const authRequiredSource = await readSource('src/components/friend/FriendAuthRequiredState.vue')
  const friendViewSource = await readSource('src/views/FriendView.vue')
  const friendPanelSource = await readSource('src/components/friend/FriendPanel.vue')
  const entryPageSource = await readSource('src/views/EntryPage.vue')

  assert.match(authRequiredSource, /登入後才能使用好友功能/)
  assert.match(authRequiredSource, /前往登入/)
  assert.match(friendViewSource, /loadFriendDataIfAllowed/)
  assert.match(friendViewSource, /friendStore\.clearFriendData\(\)/)
  assert.match(friendViewSource, /name: "Entry"/)
  assert.match(friendViewSource, /query: \{ auth: "login" \}/)
  assert.match(friendPanelSource, /FriendAuthRequiredState/)
  assert.match(friendPanelSource, /panelSummary/)
  assert.match(friendPanelSource, /:disabled="!friendStore\.canUseFriendSystem"/)
  assert.match(friendPanelSource, /name: "Entry"/)
  assert.match(entryPageSource, /route\.query\.auth/)
  assert.match(entryPageSource, /<LoginContent @close="closeLoginModal" \/>/)
})
