import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const gameStageSource = readFileSync('src/components/game/ui/GameStage.vue', 'utf8')
const cardPlaySource = readFileSync('src/composables/useGameStageCardPlay.js', 'utf8')
const socketActionsSource = readFileSync('src/composables/useGameSocketActions.js', 'utf8')
const gameViewSource = readFileSync('src/views/GameView.vue', 'utf8')
const settingsSource = readFileSync('src/components/game/ui/GameSettingsModal.vue', 'utf8')
const gameHandlersSource = readFileSync('server/src/socket/gameHandlers.js', 'utf8')

test('game stage exposes turn timeout and computer-finish controls', () => {
  assert.match(gameStageSource, /turnSecondsLeft = ref\(30\)/)
  assert.match(gameStageSource, /"auto-play-timeout"/)
  assert.match(gameStageSource, /class="turn-countdown" role="timer"/)
  assert.match(gameStageSource, /class="turn-countdown__hourglass"/)
  assert.match(gameStageSource, /\.turn-countdown \{[\s\S]*left: 14px;[\s\S]*bottom: 18px;/)
  assert.match(gameStageSource, /\.turn-countdown \{[\s\S]*border: 0;[\s\S]*font-weight: 700;/)
  assert.match(gameStageSource, /\.turn-countdown \{[\s\S]*background: transparent;[\s\S]*box-shadow: none;/)
  assert.match(gameStageSource, /@media \(max-width: 767px\) \{[\s\S]*\.turn-countdown \{[\s\S]*min-height: 28px;[\s\S]*font-size: 11px;/)
  assert.match(gameStageSource, /@media \(max-width: 767px\) \{[\s\S]*\.turn-countdown__hourglass \{[\s\S]*width: 10px;[\s\S]*height: 14px;/)
  assert.match(gameStageSource, /@keyframes turn-hourglass-spin/)
  assert.match(gameStageSource, /"skip-computer-finish"/)
  assert.match(gameStageSource, /\.skip-computer-button \{[\s\S]*bottom: 92px;[\s\S]*min-height: 40px;[\s\S]*padding: 9px 16px;/)
  assert.match(gameStageSource, /props\.isSkippingComputerFinish/)
  assert.match(gameStageSource, /!isTutorialBlocking\.value/)
  assert.match(gameStageSource, /areTurnStartAnimationsIdle/)
  assert.match(gameStageSource, /!isInitialRoundDrawAnimating\.value/)
  assert.match(gameStageSource, /!isRoundStartNoticeOpen\.value/)
  assert.match(gameStageSource, /!isTurnNoticeOpen\.value/)
  assert.match(gameStageSource, /areAutoNoticesSuppressed/)
  assert.match(gameStageSource, /isSkipSettlementActive/)
  assert.match(gameStageSource, /playSkippedRoundSettlement/)
  assert.match(gameStageSource, /const protectedPlayerIds = computed/)
  assert.match(gameStageSource, /:protected-player-ids="protectedPlayerIds"/)
  assert.match(gameStageSource, /v-if="isSkippingComputerFinish && !isSkipSettlementActive"/)
  assert.match(gameStageSource, /skip-settlement-overlay/)
  assert.match(gameViewSource, /game:auto-play-timeout/)
  assert.match(gameViewSource, /game:simulate-computer-finish/)
  assert.match(gameViewSource, /\{ timeout: 30000 \}/)
  assert.match(gameViewSource, /isSkippingComputerFinish\.value/)
  assert.match(gameViewSource, /data\.settlementState \?\? data\.state/)
  assert.match(gameViewSource, /playSkippedRoundSettlement/)
  assert.match(gameViewSource, /applyGameStatePayload\(\{ state: data\.state \}\)/)
  assert.match(gameViewSource, /isSkippingComputerFinish,/)
  assert.match(cardPlaySource, /props\.isSkippingComputerFinish/)
  assert.match(socketActionsSource, /isSkippingComputerFinish = ref\(false\)/)
  assert.match(socketActionsSource, /isSkippingComputerFinish\.value[\s\S]*handleSocketGameAction/)
  assert.match(gameHandlersSource, /skippingComputerFinishRooms = new Set/)
  assert.match(gameHandlersSource, /skippingComputerFinishRooms\.has\(roomCode\)/)
  assert.match(gameHandlersSource, /await waitForActiveComputerTurn\(roomCode\)/)
})

test('settings modal fits mobile without its own scroll', () => {
  assert.match(settingsSource, /@media \(max-width: 760px\) \{[\s\S]*\.settings-dialog \{[\s\S]*overflow: hidden;/)
  assert.match(settingsSource, /@media \(max-width: 760px\) \{[\s\S]*\.settings-header \{[\s\S]*min-height: 48px;/)
  assert.match(settingsSource, /@media \(max-width: 760px\) \{[\s\S]*\.audio-grid \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/)
})

test('intern target choices exclude eliminated players', () => {
  assert.match(cardPlaySource, /if \(player\.isEliminated\) \{\s*return false;\s*\}/)
})

test('settings return-lobby action is a surrender confirmation', () => {
  assert.match(settingsSource, /確認投降/)
  assert.match(settingsSource, /放棄對局無法領取結算獎勵/)
  assert.match(settingsSource, /openConfirmation\('return-lobby'\)/)
  assert.doesNotMatch(settingsSource, /OFFICE POLITICS|AUDIO|GAME|CONFIRM ACTION/)
})
